### ISSUE TITLE
suyee.mon@savethechildren.org on build #4: 0ffddlllllrdetlm1.                     Patients  af         …

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceMyanmarApp#1]
Feedback from suyee.mon@savethechildren.org : 0ffddlllllrdetlm1.                     Patients  af                              this app doesnt allow the pa v back  space. See akl my mistajes

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5854527e2d2ddd0100822e74/5858f2a038293b0100c0b22f/b95729fc-ddd5-4a40-aacf-cf55b3ecc548.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Fri Jan 06 2017 04:20:21 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-G7102</td></tr><tr><td>Screen size</td><td>720</td></tr><tr><td>Screen size</td><td>720px by 1280px</td></tr><tr><td>Battery</td><td>15% Charging</td></tr><tr><td>Memory free</td><td>284 MB / 1373 MB</td></tr></table>

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/5854527e2d2ddd0100822e74/feedback?fid=586f1b050bba28010075ad56&bnum=4)

**Comment by ifoche** [comment]
@MonSuYee I don't understand this issue. So you're not allowed to delete values on age textfield? I've just tested it and it works for me without problems

**Comment by MonSuYee** [comment]
Hi, Ignacio,
Sorry my comment was very confusing. I wrote it on the Buddybuild, and was not able to do "backspacing". It is not about the text field on Malaria App. It is about Buddybuild app.

**Comment by ifoche** [comment]
oh, I see. I'm so sorry, but we do not control the buddybuild textfield, as it's provided directly by buddybuild...but maybe if we can define it better, we can create a bug report for buddybuild so they can solve it as soon as possible. I've tested it and I cannot reproduce the problem. It looks like a bug with your keyboard, more than a bug on buddybuild itself. However, if you click on the top left number in this issue ("1" for this case) it will take you to github site, where you can drag & drop images in the comments and not only text. So maybe you want to upload a new comment with an image showing the problem and your keyboard? that may help.

Thanks!

**Comment by MonSuYee** [comment]
Thanks! I think I will just go around that problem.

**Comment by ifoche** [comment]
ok...so I'm closing this issue. Please re-open it if you decide to create the bug report for buddybuild or dig a bit more on the problem. Thanks for the effort.
