### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MonSuYee** [EyeSeeTea/SurveillanceMyanmarApp#12]
It is still crashing really bad.

**Comment by ifoche** [comment]
Hi @MonSuYee. Can you uninstall and reinstall again the app, and let me know if you still have this problem?

**Comment by MonSuYee** [comment]
Yeah, uninstalling and reinstalling makes it run again. 
But I get the "Unfortunately, malaria case-based reporting has stopped" message after a while again.

**Comment by ifoche** [comment]
ok, I think we have identified that crash. Thanks for reporting, we'll take care of it.
