### ISSUE TITLE
Provide link to final treatment matrix in the app

### ISSUE THREAD

**Issue by rodmelia** [EyeSeeTea/SurveillanceMyanmarApp#24]
Please provide current values for the treatment matrix embedded in the app 

Please download them in a similar layout to the original spreadsheet 
https://docs.google.com/spreadsheets/d/1-OwcYBSeRLgQ482tm_KURDnBP2M-da0wTMmppcdt1cs/edit#gid=0

**Comment by rodmelia** [comment]
New - please estimate adding an option on the development section of the app to send treatment matrix currently contained in the app in a csv, formatted in such a way that it can be analyzed (for example via pivot)

**Comment by ifoche** [comment]
Please follow this link to see the current Treatment Matrix:
https://drive.google.com/open?id=19GeSwSiKLVVKKRkY_gyPu8Og2Mj--Vo9WyICcm0sjvo
