### ISSUE TITLE
Stock Calculation Error in alpha realease

### ISSUE THREAD

**Issue by myothetnaingwin** [EyeSeeTea/SurveillanceMyanmarApp#42]

**Comment by myothetnaingwin** [comment]
![Stock Calculation Error.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab67fe17326ad0013b55330/125516c66e82c728ace21e0d46db80952089c38a8ee5bc56a85ce49d264867563b16ac3932c9a138ad4d71040c1b5ca6535d5741f8f88022a5b63b728f0f5fe5d26d5f73c23412aced9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3c1f0c1989fd5a31a19948da15.JPG)

Please see the attached photo. In photo, there are 3 tested cases and of which 2 cases needs to give ACT-6. But in Stock Module and Monitoring tab, it shows 4 ACT-6 usage.

**Comment by ifoche** [comment]
@myothetnaingwin, could you please provide the exact answers to all questions in those 3 surveys so I can replicate the same situation?

**Comment by rodmelia** [comment]
@myothetnaingwin  @krosecrans - please don't forget to send the details for the 3 cases, so we can reproduce the problem.

**Comment by myothetnaingwin** [comment]
This issue was found by one of our colleague. I tried on the app but I could not produce that issue.
Sorry for my late reply as I was on trip with no internet connection.

**Comment by rodmelia** [comment]
@myothetnaingwin as we cannot reproduce the bug we will tag it as invalid
