### ISSUE TITLE
suyee.mon@savethechildren.org on build #4:

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceMyanmarApp#5]
Feedback from suyee.mon@savethechildren.org : 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5854527e2d2ddd0100822e74/5858f2a038293b0100c0b22f/2d8ef4f8-245a-4783-8b52-d0485484a033.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Jan 11 2017 06:40:44 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-G7102</td></tr><tr><td>Screen size</td><td>720</td></tr><tr><td>Screen size</td><td>720px by 1280px</td></tr><tr><td>Battery</td><td>30% Unplugged</td></tr><tr><td>Memory free</td><td>220 MB / 1373 MB</td></tr></table>

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/5854527e2d2ddd0100822e74/feedback?fid=5875d36cd60df10100f3367f&bnum=4)

**Comment by MonSuYee** [comment]
Four issues here
1. The second question here should be "Where did you travel?"

2. We did not want sub-text to the question disappear here. (Within 1 month)

3. We want the categories to be in the following order: 
a. Plantation
b. Forest
c. Other Worksites
d. Other village/city

4. the second question should appear only if the answer to first question is "Yes" (Just like LLIN ownership appears only if the answer to LLIN usage is "No"). 

I signed up at PO Editor Website with user name "Su Yee Mon". Thought I could spare you for the first three issues if I edited in myself, but I am quite unaware of the timeline when I could start editing it.

**Comment by ifoche** [comment]
@MonSuYee. For the issue 3 I will take care of it (ordering options is more complicated than just translation). It's perfecly fine if you take care of the first 2 issues. Well take care of the other 2.

**Comment by ifoche** [comment]
@MonSuYee, please, just notify me whenever you're finished with the translations to incorporate them to the code

**Comment by ifoche** [comment]
BTW @MonSuYee, can you accept the github invitation to the MM Testers Team?

**Comment by MonSuYee** [comment]
Hi, Ignacio,
I have accepted the invitation. 

For issue 1 &2, for PO Editor edition, I think I would need permission or some link to go to the specific site? 

And the only change in translation would be "Work site" to "Other Work site" (Issue 3); 
![image](https://cloud.githubusercontent.com/assets/24870381/22051249/ee26cff4-dd6f-11e6-84e2-599dcbda0e12.png)

**Comment by MonSuYee** [comment]
Hi, Ignacio,
I have accepted the invitation.

For issue 1 &2, for PO Editor edition, I think I would need permission or some link to go to the specific site?

And the only change in translation would be "Work site" to "Other Work site" (Issue 3);
image

I accidentally closed the issue, and re-openned it.

**Comment by ifoche** [comment]
@MonSuYee sorry for the delay answering you, but I think you already entered and edited in POEditor, right?

**Comment by MonSuYee** [comment]
Yes, have done, Ignacio.
