### ISSUE TITLE
suyee.mon@savethechildren.org on build #4:

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/SurveillanceMyanmarApp#6]
Feedback from suyee.mon@savethechildren.org : 

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/5854527e2d2ddd0100822e74/5858f2a038293b0100c0b22f/7d9329d2-62b1-4df8-9e0b-9d5e762c0be1.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Wed Jan 25 2017 04:47:35 GMT+0000 (UTC)</td></tr><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>SM-G7102</td></tr><tr><td>Screen size</td><td>720</td></tr><tr><td>Screen size</td><td>720px by 1280px</td></tr><tr><td>Battery</td><td>74% Unplugged</td></tr><tr><td>Memory free</td><td>253 MB / 1373 MB</td></tr></table>

 [Link to buddybuild feedback from build 4](https://dashboard.buddybuild.com/apps/5854527e2d2ddd0100822e74/feedback?fid=58882de7d2a7d70100a1feb8&bnum=4)

**Comment by MonSuYee** [comment]
Pv and Pf are reversed!
